import { Types, isValidObjectId } from 'mongoose';
import { z } from 'zod';

// ---------------------------------------------------------------------------------------------
// Vocabularies and limits
// ---------------------------------------------------------------------------------------------

export const bookingStatuses = ['confirmed', 'cancelled'] as const;

// BK08 — the cap on one submission. A band is a handful of people, not a coach party, and the
// claim runs one round trip per spot: an unbounded array is a way to hold a connection open while
// mutating the same jam session document dozens of times.
export const MAX_SPOTS_PER_BOOKING = 10;

// ---------------------------------------------------------------------------------------------
// Reusable field pieces
// ---------------------------------------------------------------------------------------------

// `slotId` and `spotId` are `randomUUID()` values generated by `generateSlots`, never ObjectIds —
// they exist so `arrayFilters` can match on a named field rather than on a nested `_id`. Validating
// the format here means a malformed id is a 400 rather than a claim that silently matches nothing
// and reports the spot as taken.
const uuidField = z.uuid('must be a valid id');

// ---------------------------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------------------------

// BK10 — a strictObject, so the server-owned fields enforce themselves. `musicianId` comes from the
// access token, `groupId` and `qrCode` are generated per submission, and `status` is only ever
// changed through the cancel endpoint. A client sending any of them gets a 400 rather than having
// the value quietly ignored.
//
// One request claims several spots inside *one* slot — that is what the booking flow asks for, and
// it is why `slotId` is a single value while `spotIds` is an array. Booking two different slots is
// two submissions, two groups, two QR codes.
const bookingFields = z.strictObject({
  jamSessionId: z.string().refine(isValidObjectId, 'must be a valid id'),
  slotId: uuidField,

  spotIds: z
    .array(uuidField)
    .min(1, 'at least one spot is required')
    .max(MAX_SPOTS_PER_BOOKING, `max is ${MAX_SPOTS_PER_BOOKING} spots per booking`),

  // BK09 is deferred, so this is plain optional rather than "required when claiming more than one
  // spot". It is only ever a label on the client's booking card.
  bandName: z
    .string()
    .trim()
    .min(2, 'min length is 2 chars')
    .max(120, 'max length is 120 chars')
    .optional(),
});

// BK08 — the same spot twice in one submission. The second claim would fail against `bookingId:
// null` and take the whole submission down with it (BK07), so the musician would see "that spot is
// not available" about a spot they had just been given. Rejecting up front says what actually
// happened.
export const bookingInputSchema = bookingFields.refine(
  ({ spotIds }) => new Set(spotIds).size === spotIds.length,
  { error: 'each spot can only be claimed once', path: ['spotIds'] },
);

export type BookingInput = z.infer<typeof bookingInputSchema>;

// `groupId` is a uuid rather than an ObjectId, so `idParamSchema` cannot check it — it would reject
// every valid group. Same job, different format: a malformed value is a 400 here instead of a query
// that quietly matches nothing and reports the group as missing.
export const groupIdParamSchema = z.object({
  groupId: uuidField,
});

export type GroupIdParams = z.infer<typeof groupIdParamSchema>;

// ---------------------------------------------------------------------------------------------
// Query
// ---------------------------------------------------------------------------------------------

// A strictObject, like the jam session query: `?jamSession=abc` would otherwise be ignored and
// return every booking the caller can see, and a filter that quietly does nothing is a worse bug
// than one that says it doesn't recognise the parameter — here especially, since the unfiltered
// answer looks plausible right up until it doesn't.
//
// Deliberately not a `status` filter as well. Cancelled bookings are the record of who dropped out,
// so both readers want them in the list rather than filtered away, and `status` is already on every
// row for the client to split on.
export const bookingQuerySchema = z.strictObject({
  jamSessionId: z.string().refine(isValidObjectId, 'must be a valid id').optional(),
});

export type BookingQuery = z.infer<typeof bookingQuerySchema>;

// No update schema. BK15 is deferred: there is no PATCH /bookings/:id, because the only thing it
// would have edited is `bandName`. Dropping one instrument is cancelling one booking document, and
// moving to another slot is cancel + rebook — a spot can only ever be acquired through the atomic
// claim, so an "edit" that changed `slotId` would be a rebook wearing a different verb.

// ---------------------------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------------------------

// Mongoose hands back ObjectId instances, not strings. Normalised here so the client never has to
// deal with `{ $oid: ... }` shaped values. (Defined locally rather than imported from
// `jamSessionSchema` — three lines is a smaller cost than a dependency between two schema files.)
const objectIdOutput = z
  .union([z.string(), z.instanceof(Types.ObjectId)])
  .transform((value) => String(value));

// The base shape, with both references left as plain ids. This is what a freshly created booking
// looks like, since nothing has been populated yet.
export const bookingOutputSchema = z.object({
  id: z.string(),

  // shared by every booking made in one submission. The client's "My bookings" groups by this to
  // draw a band's five spots as a single card.
  groupId: z.string(),

  jamSessionId: objectIdOutput,
  slotId: z.string(),
  spotId: z.string(),
  musicianId: objectIdOutput,

  // Copied off the spot at claim time rather than looked up on every read. Safe by construction:
  // JS10 freezes `startTime`, `endTime`, `slotDurationMinutes` and `instrumentTemplate` the moment
  // any spot on a session is booked, so these values cannot drift while the booking is live. It is
  // what lets "My bookings" render a card without fetching the session and walking `slots[]`.
  instrument: z.string(),
  label: z.string(),
  slotStartTime: z.string(),
  slotEndTime: z.string(),

  bandName: bookingFields.shape.bandName,

  status: z.enum(bookingStatuses),

  // an opaque token, not an image. The client renders the QR from it; keeping a base64 PNG in the
  // document would multiply its size for something the client can draw in a line of JSX.
  qrCode: z.string(),

  createdAt: z.date(),
  updatedAt: z.date(),
});

export type BookingOutput = z.infer<typeof bookingOutputSchema>;

// Plain `z.object`s, not strictObjects: these parse *populated mongoose documents*, which carry
// their whole prototype — `_doc`, `$__parent`, `save` and eighty more. A strictObject reports every
// one of them as an unrecognized key and refuses the parse.
const jamSessionSummarySchema = z.object({
  id: z.string(),
  title: z.string(),
  date: z.date(),
  venueName: z.string(),
  status: z.string(),
  // Only `formatted` — the one line the venue actually typed. `lat`/`lng` exist on the stored
  // address and are left out here because nothing on a booking draws a map, and a projection that
  // returns them anyway is a projection nobody is reading.
  address: z.object({ formatted: z.string() }),
});

// BK18 — how to reach the people playing at your night, and nothing more. The controller's populate
// projection is the enforcement rather than a promise made here: a field that was never selected
// cannot be returned by this schema whatever it declares.
//
// The email is deliberate. A venue that has to call a night off, or move a slot, otherwise has no
// way to tell anyone who signed up — and everyone in this list chose to book that venue's session.
// What the rule still prevents is turning a name into an account: `GET /users/:id` is self-only and
// there is no users index, so nothing here reaches a musician the caller has no booking with.
const musicianSummarySchema = z.object({
  id: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
});

// What the read endpoints return. `.populate()` replaces the value *at the same path*, so mongoose
// hands back a document sitting under the key `jamSessionId` — which would leave the client writing
// `booking.jamSessionId.title`. The transform renames both paths on the way out, so the response
// says `jamSession` and `musician`, which is what they now hold.
export const bookingDetailOutputSchema = bookingOutputSchema
  .extend({
    jamSessionId: jamSessionSummarySchema,
    musicianId: musicianSummarySchema,
  })
  .transform(({ jamSessionId, musicianId, ...booking }) => ({
    ...booking,
    jamSession: jamSessionId,
    musician: musicianId,
  }));

export type BookingDetailOutput = z.infer<typeof bookingDetailOutputSchema>;
